### ISSUE TITLE
Bounding boxes filtering takes 70% of total augmentations time

### ISSUE THREAD

**Issue by AL3708** [albumentations-team/albumentations#1197]
## 🐛 Bug

I'm using albumentations to augment images for object detection task (with bounding boxes). I have images that contains 100-500 boxes of small objects per image (500x700px). When i call albumentations.Compose method and profile it with cProfile, it shows that 70% of total augmentations time was boxes filtering (filter_bboxes(...) form bbox_utils.py). Boxes filtering takes ~22000ms of ~32000ms total time. Call graph:
![image](https://user-images.githubusercontent.com/103039601/174785964-e7f0bac0-780c-4120-abc9-4678f1431f8e.png)

## To Reproduce

1. Load 500x700px image
2. Generate 100-500 small bounding boxes (ex 30x15px)
3. Apply augmentations for image and boxes with albumentations.Compose method
4. Profile inference time with cProfile

## Expected behavior

Bounding boxes postprocessing time should be << than image augmentations time

## Environment

 - Albumentations version: 1.2.0
 - Python version: 3.10.5
 - OS: Windows 10
 - How you installed albumentations): pip

**Comment by Dipet** [comment]
Hi, thanks for reporting this issue.
The library has a problem if you have a lot of bboxes, but since must people do not  usually use more than dozens of bboxes we didn't think that this is a real problem.
We will try to fix the problem, but it may take a long time, because a lot of changes needed.

**Comment by Dipet** [comment]
To solve this problem we need to process bboxes as batches using numpy. But ыштсу all ща our transforms works with bboxes as tuples these changes are complicated.

**Comment by GdoongMathew** [comment]
@AL3708 and @Dipet 
I've implemented some of the bboxes transforms with numpy in [my repo](https://github.com/GdoongMathew/albumentations). But there's a little problem in this, unless you have more then 20 bounding boxes in one image, you can't really observe any true improvements, or even encounter some speed degradation since the boxes will have to be converted back and forth within each apply_to_bboxes. 
Here's some experiments.

|methods|for loop with 5 bboxes|numpy ops with 5 bboxes|for loop with 10 bboxes|numpy ops with 10 bboxes|for loop with 20 bboxes|numpy ops with 20 bboxes|
|---|---|---|---|---|---|---|
|HorizontalFlip|3151|2490|1802|2409|1148|1995|
|VerticalFlip|3195|2601|1864|2460|1147|2112|
|Flip|3223|2448|1558|2449|1132|2161|
|Rotate|349|342|312|355|277|337|
|SafeRotate|266|264|243|254|218|253|
|RandomRotate90|778|785|745|801|596|766|
|ShiftScaleRotate|333|330|311|336|256|340|
|Transpose|677|638|626|640|515|631|
|Pad|700|625|639|608|502|629|
|Perspective|269|264|241|280|193|283|
|RandomCropNearBBox|6327|3152|3532|3015|1970|2623|
|BBoxSafeRandomCrop|2241|1931|1293|1849|740|1708|
|CenterCrop|5309|2885|3019|2710|1626|2431|
|Crop|5323|2751|3044|2534|1729|2335|
|CropAndPad|809|728|697|722|546|712|
|RandomCropFromBorders|3141|2212|1942|2184|1096|1985|
|Affine|373|417|321|429|227|424|

Overall, I think the overall performance can be improved further if someone can figure out a way to remove the converting process while still do the label_field filtering.

By the way, the average bboxes / image in COCO Dataset is 7.19 based on [this](https://www.researchgate.net/figure/Dataset-statistics-Number-of-images-and-objects-per-split-average-number-of-objects_tbl1_324717066), so unless your application is in some manufacturing industry, which might have dozens of bboxes in one image waiting for prediction, other than that, this numpy operation currently won't help.
