### ISSUE TITLE
Slow installation of Albumentations v1.2 on Apple sillicon

### ISSUE THREAD

**Issue by antifriz** [albumentations-team/albumentations#1204]
Albumentations v1.2 takes a lot of time to install on Apple sillicon. At the same time v1.1 succeeds in a few seconds.

## To Reproduce

1. Grab an Apple sillicon
1. `pip install albumentations==1.2`
1. wait for a lot of time and hope you have a good environment for building `numpy==1.19.3`

## Expected behavior

Not needing to compile numpy from source.

## Additional context

This [commit](https://github.com/albumentations-team/albumentations/commit/b0707c567e1d279ad384194a2117ba5b116efbd2) is to blame. It forces the installation of `scikit-image==0.18.2` which isn't prebuilt for Apple sillicon so it needs to be built using `numpy==1.19.3` which isn't prebuilt too. Builing it takes a lot of time, and fails if environment isn't correctly set.

**Comment by Dipet** [comment]
I am not sure if we can fix this problem, because I do not know how to check that numpy is prebuilt for your hardware.
Maybe it only took a few second to install the old version because you already installed numpy?
Have you tried installing v1.1 in a clean environment?
I don't have an Apple with M1 CPU, so I can not check and fix this issue.

The scikit-learn documentation says that the only way to get prebuilt libraries is to use conda https://scikit-learn.org/stable/install.html#installing-on-apple-silicon-m1-hardware

**Comment by ternaus** [comment]
Removed scikit-learn depencency in https://github.com/albumentations-team/albumentations/pull/1854
