### ISSUE TITLE
Add check that masks and image have the same height and width

### ISSUE THREAD

**Issue by Dipet** [albumentations-team/albumentations#1299]
This needed to avoid problems inside spatial-level transforms when params generated based on image shapes, for example pad and crop augs.

**Comment by Andredance** [comment]
I would like to take this one!

**Comment by Andredance** [comment]
@Dipet I have two proposals for this issue:
* We can add a check for the same height and width inside __Compose__ class's method ___check_args__. It will work I think, but it will not cover the problem if augmentations are used without __Compose__ class 
* We can add a similar __check_args_ method to BasicTransform class. I think it will cover the usage of augs without Compose class but it will cause some overhead because __check_args_ for BasicTransform would be called for every augmentation call.

What do you think?

**Comment by Dipet** [comment]
I think check inside `Compose` is enough. In common usage of augs outside of `Compose` is incorrect.
