### ISSUE TITLE
Motion blur does not shift the mask

### ISSUE THREAD

**Issue by YJonmo** [albumentations-team/albumentations#1328]
Hi there, 

When applying the motion blur, the image will shifts but the mask remain the same. 
Is it supposed to be like this or is a bug? 
Here is an example of the an image before and after motion blur and its corresponding mask.

You can see the amount of the movement based on the superimposed bar on the chest of the player.

![image](https://user-images.githubusercontent.com/12040950/197656294-da529beb-7fe1-457b-99cf-90bc8bd888f0.png)

**Comment by Dipet** [comment]
This is the correct behavior because MotionBlur only transforms the image.

**Comment by YJonmo** [comment]
Thanks. 
But if I use the transformed mask and apply it to the motion blurred image, then there will be a lot of left overs from the grass in the mask and as well player on the grass. 
Is there any way to shift the mask the same amount that the player is shifted?

**Comment by Dipet** [comment]
It is might be hard because MotionBlur is a convolution with some kernel. We can not just simple convolve mask too, because this  operation will change mask values. Maybe we could convolve mask, take new mask, make dilation with same filter size, after that take mask values from dilated mask based on convolved mask. But this operation very slow.

We need to do research to find a way how to properly change the mask.
