### ISSUE TITLE
Chromatic Abberation

### ISSUE THREAD

**Issue by KulikDM** [albumentations-team/albumentations#1386]
Hi, I'm not sure if any augmentation like this exists in Albumentations. But if not, chromatic abberation would be a great addition. Chromatic abberation occurs when a camera lens fails to focus all the colors at the focal point of the lens due to dispersion. This effect can easily be replicated in python. Below is an example code of the implementation:
``` 
import numpy as np

image[:, :, 0] = np.roll(image[:, : ,0], -px_shift * 2)
image[:, :, 1] = np.roll(image[:, :, 1], -px_shift)
```
where `px_shift` is the number of pixels the color is shifted by and the direction is set by the sign in front of the pixel shift. Both the direction and the pixel shift can be randomized with the pixel shift also being able to be assigned a random range.

**Comment by mrsmrynk** [comment]
Simply shifting the 2 channels (blue and red) would apply the chromatic aberration effect to the whole image.
This might not be the desired effect since the color fringing typically occurs only at the edges of the image.

To simulate lateral chromatic aberration, the shift should be applied to the individual channels separately with respect to the radial distance from the center of the image.

This can be done by splitting the image into its RGB channels, applying a slight amount of distortion to the blue and red channels, and then merging the channels back together.
The border mode should be set to `cv2.BORDER_REFLECT` to avoid black borders in the channels, if the distortion gets quite large.

If this transform seems useful, I would like to implement it as an `ImageOnlyTransform`.

**Comment by KulikDM** [comment]
Great to hear back on this! 
You are totally right, my implementation was an overly simplistic one and lateral chromatic aberration as you described would be much more realistic. If it looks like (https://smallpond.ca/jim/photomicrography/ca/index.html) then you have super excited. Please implement it, by all means, looking forward trying it out.

**Comment by mrsmrynk** [comment]
Already implemented this for our augmentation pipeline. The results look like this:

<div align="center">
  <a href="https://i.imgur.com/tUiymXQ.jpeg">
    <img src="https://i.imgur.com/tUiymXQ.jpeg" width="30%">
  </a>
  <a href="https://i.imgur.com/Jc2b5kG.jpeg">
    <img src="https://i.imgur.com/Jc2b5kG.jpeg" width="30%">
  </a>
  <a href="https://i.imgur.com/OGhQCTf.jpeg">
    <img src="https://i.imgur.com/OGhQCTf.jpeg" width="30%">
  </a>
  <p>
    <b>Left:</b> Original, <b>Middle:</b> Subtle chromatic aberration, <b>Right:</b> Strong chromatic aberration
    <br>(Image is from our internal mobile mapping dataset)
  </p>
</div>

Waiting for feedback from @albumentations-team, then I'll make a PR :)

**Comment by ternaus** [comment]
@mrsmrynk Looks great.

Waiting for a PR :)

**Comment by ternaus** [comment]
Added by @mrsmrynk in https://github.com/albumentations-team/albumentations/pull/1589
