### ISSUE TITLE
[tech debt] Move in website to the repo

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#1569]
We need to be sure that the docs are compiled when we update the repo.

Doing it in separate repositories is a pain. 

In this case, a mono repo could be better.

**Comment by saigontrade88** [comment]
Hello,
 Today I have got an issue when accessing autoalbument documentation at https://albumentations.ai/docs/autoalbument/. Can you help check if this issue can be fixed? Many thanks.

**Comment by ternaus** [comment]
@saigontrade88 fixed.

Would you consider becoming a sponsor for Albumentations? 

https://github.com/sponsors/albumentations-team

**Comment by saigontrade88** [comment]
@ternaus thanks and I did a one-time donation because I am a student. Can you help check the reference link at [https://tensorboard.dev/experiment/ZleMHe73QCGzPeDCRpFLfA/](url) in the following URL https://albumentations.ai/docs/autoalbument/metrics/#examples-for-metric-values? It is no longer accessible because TensorBoard.dev service has been stopped.

**Comment by ternaus** [comment]
Thanks for your donation. Every dollar counts :)

I will look at metrics, but I cannot promise. 

It was generated a long time back by @creafz , who focuses on other projects.

But I will take a look, anyway.
