### ISSUE TITLE
Interpolation 

### ISSUE THREAD

**Issue by wamiq-reyaz** [albumentations-team/albumentations#233]
It seems like all the functions that deal with masks do not allow you to choose the interpolation type applied to the mask, only the image. Is the default on the masks always nearest neighbor?

**Comment by albu** [comment]
yes

**Comment by wamiq-reyaz** [comment]
Thanks a lot for answering.

**Comment by albu** [comment]
looks like it's about passing one more parameter in constructor

**Comment by ternaus** [comment]
@wamiq-reyaz Feel free to create a  PR with this feature.

**Comment by wamiq-reyaz** [comment]
> @wamiq-reyaz Feel free to create a PR with this feature.

Sounds enticing, I am busy till the end of this month, but sure I will give it a shot.

**Comment by Dipet** [comment]
**Description**
For implement this feature we need remove hardcoded `INTER_NEAREST` from `DualTransform`.

At all spatial transforms, that change image size (like `Resize`) and/or has `interpolation` flag, implement ability to set interpolation mode in `apply_to_mask` method if it exists, or in `apply` method otherwise.

**Related files**
* `albumentations/core/transforms_interface.py`
*  `albumentations/augmentations/transforms.py`

**Comment by rashmi43** [comment]
Can I take this up?

**Comment by Dipet** [comment]
@rashmi43 Yes, you can

**Comment by ternaus** [comment]
@wamiq-reyaz 

- Added an option to choose interpolation for mask for every transform that has `mask_interpolation`
- Added an option to define `mask_interpolation` in Compose that overrides ones defined in individual transforms
