### ISSUE TITLE
Rotate without crop

### ISSUE THREAD

**Issue by IgorDavidyuk** [albumentations-team/albumentations#303]
## 📚 Documentation
I am trying to transform images with keypoints and I can not lose any keypoint.
I couldn't find an option to rotate an image without corners being cropped.
Please indicate if it is possible.

**Comment by SunQpark** [comment]
Definition of rotating transforms use [F.rotate](https://github.com/albumentations-team/albumentations/blob/4f35cda5adf73ab8ceacbba827400a1348cfb77f/albumentations/augmentations/functional.py#L187) internally. Image corners are being cropped since this function uses opencv which crop images by default. 

I think having an option to expand images instead of crop would be nice. Like `expand` argument in [torchvision.RandomRotation](https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.RandomRotation)

[This stackoverflow answer](https://stackoverflow.com/a/47248339/8503884) might be helpful implementing this.
