### ISSUE TITLE
Do not install opencv-python when there is already opencv-contrib-python

### ISSUE THREAD

**Issue by sluki** [albumentations-team/albumentations#602]
Even better would be to allow human to select which OpenCV wrapper human wants as an extra (e.g. albumentations[opencv-contrib-ptyhon-headless]==0.4.5) and use opencv-python-headless as a default. I already see that there is some trick to use opencv-python-headless only if there is no opencv-python, but there are more wrappers for OpenCV.

**Comment by Dipet** [comment]
Yes in PYPI we can find many wrappers around OpenCV. But our library is not focused on manage packages dependencies. We added hack for opecv-python and opencv-python-headless because they are the most must popular packages.

If you have or need other wrappers you can install library with flag `--no-deps`.
