### ISSUE TITLE
rotate with expand

### ISSUE THREAD

**Issue by neverrop** [albumentations-team/albumentations#642]
in PIL.Image, there is a rotate(angle, expand=True) to rotate without cropping bounders, It seems there is no similar method or op to use in albumentations.

**Comment by sonack** [comment]
+1

**Comment by thomas0809** [comment]
I don't think this issue is resolved with SafeRotate. SafeRotate compresses the rotated image to fit in the original size. Is it possible to skip the compression step? I.e. [torchvision.transform.RandomRotation](https://pytorch.org/vision/stable/transforms.html#torchvision.transforms.RandomRotation) with expand=True

**Comment by Dipet** [comment]
Try to use [Affine](https://albumentations.ai/docs/api_reference/augmentations/geometric/transforms/#albumentations.augmentations.geometric.transforms.Affine) with `fit_output` parameter
