### ISSUE TITLE
Training with tf.data pipeline doesn't work

### ISSUE THREAD

**Issue by nkaenzig** [albumentations-team/albumentations#669]
## 🐛 Bug

On [https://albumentations.ai/docs/examples/tensorflow-example/](https://albumentations.ai/docs/examples/tensorflow-example/) there is an example on how to integrate albumentations with tf.data. 
The example notebook runs as expected without error. However, when trying to use the created tf.data pipeline to train a model using Tensorflow's fit() method, an error is thrown (see below).

## To Reproduce

Here you can find a notebook where I just added a model and model.fit() call to the example Notebook from the doc, to reproduce the error:

https://colab.research.google.com/drive/1x9_UST1bW90PI8-t2gvr5chK_ySgrmYk?usp=sharing

## Expected behavior

When calling model.fit(ds_alb, epochs=1) the following error is thrown:

> ValueError: Input 0 of layer sequential_4 is incompatible with the layer: its rank is undefined, but the layer requires a defined rank.

## Environment

 - Albumentations version (e.g., 0.1.8): 0.4.6
 - TensorFlow: 2.2

**Comment by benihime91** [comment]
Please open access.

**Comment by benihime91** [comment]
I tried `fit` on my own model. It worked fine . Maybe something wrong with your `model architecture`.?
Well, here's my `notebook` you can check it out: 
(https://github.com/benihime91/tensorflow-keras-nbs/blob/master/Copy_of_tensorflow_example.ipynb)

**Comment by nkaenzig** [comment]
> Please open access.

Just changed the access permissinos to every body. The model should be fine, as training works with the pure tensorflow tf.data pipeline example in the same notebook. Maybe only occurs with certain layers such as convolutional layers.

**Comment by benihime91** [comment]
I just tried your notebook the model's training . How exactly did u get the error?

**Comment by benihime91** [comment]
I tried running the your `model` both in `eager-execution` & `non eager-execution` seems to be working fine .

**Comment by benihime91** [comment]
Even `Functional API` works fine :

```
from tensorflow import keras
input = keras.Input(shape=(120, 120, 3))
x = keras.layers.Conv2D(32, (3, 3), activation="relu")(input)
x = keras.layers.MaxPooling2D((2, 2))(x)
x = keras.layers.Conv2D(64, (3, 3), activation='relu')(x)
x = keras.layers.MaxPooling2D((2, 2))(x)
x = keras.layers.Conv2D(64, (3, 3), activation='relu')(x)
x = keras.layers.Flatten()(x)
x = keras.layers.Dense(64, activation='relu')(x)
x = keras.layers.Dense(5, activation='softmax')(x)

model = keras.Model(input, x)
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics='accuracy')
model.fit(ds_alb, epochs=1)

115/115 [==============================] - 28s 245ms/step - loss: 1.4399 - accuracy: 0.3564
<tensorflow.python.keras.callbacks.History at 0x7f90f08d4780>
```

**Comment by benihime91** [comment]
I think the problem is while doing the `tf_ds.load` function as you can see when you load the inbuilt `dataset in tensorflow datasets using tf_ds.load()` it is automatically loading the data as a wrapper under the `tf.compat.v1.data.Dataset`. This is due to the outdated `tensorflow_datasets` version in colab
```
# load in the tf_flowers dataset
data, info= tfds.load(name="tf_flowers", split="train", as_supervised=True, with_info=True)
data

<DatasetV1Adapter shapes: ((None, None, 3), ()), types: (tf.uint8, tf.int64)>

tfds.__version__
2.1.0
```
if you lookup the definition of `DatasetV1Adapter` ---> Wraps a V2 `Dataset` object in the `tf.compat.v1.data.Dataset` API.

The latest version is `3.2.1` .

Also i tried every possible way to use a `tf.keras.Model` . These are my findings: 
- I found the error only whilst using the `Sequential API` that too if you `have your own layers as the first layers` using a `pretrained-model` as the `feature-extractor` in the `Seqential API` works fine. 
- If you `compile` the `model` using `run_eagerly=True` everything works fine. Any API `works`.
- Also while using the `functional API` I didn't find any problems all whatever the case.
- I didn't try with the `Subclassing API` (because I've never used it 😊)

Maybe need to make a note in the `tutorial` that using the `Sequentail API` will `sometimes not work ..`

**Comment by benihime91** [comment]
@Dipet I have found 2 instances where this `data pipeline doesn't` work. Should i create a PR making note of these instances?

**Comment by Dipet** [comment]
It will be great if you do it

**Comment by nkaenzig** [comment]
@benihime91 Thanks a lot for looking into it, very interesting your findings. As for your suspicion regarding the issue being related to `tf_ds.load`, I tried it as well with another dataset pipeline where I loaded images directly from .jpeg files using `tf.io.read_file`, which resulted in the same error, so it seems that isn't the issue - or at least not the only one.

`run_eagerly=True` is a good workaround for now, but I assume that this will make training significantly slower.
Very strange that the problem only arises when using the Sequential API... to me it seems that this is a bug of TensorFlow, so maybe we should open an issue in the TensorFlow repo.

**Comment by benihime91** [comment]
Yes you are correct maybe it's a bug within the `tf.keras.models.Sequential API` & `run_eagerly` does significantly make the `training` slower. 
Here's everything that I've tried so far: 
https://github.com/benihime91/tensorflow-keras-nbs/blob/master/tensorflow_example_updated.ipynb
Let me know for any changes. Thanks.
