### ISSUE TITLE
Is it possible to run bbox augmentations without having to add the labels param? Bbox labels don't make sense for my task

### ISSUE THREAD

**Issue by abecciu** [albumentations-team/albumentations#684]
After a lot of digging into the code I couldn't find a way to run augmentations on bboxes without adding the extra labels param. Am I missing something?

Bbox labels don't make sense for my task. I end up having to add an extra labels param like so:

```python
t = A.Compose(transforms, bbox_params=A.BboxParams(format='coco', label_fields=['class_labels'])
imgs, bboxes, lables = t(image = img, bboxes = [bbox], class_labels=[0])
```

Is there a way to avoid that?

**Comment by notmatthancock** [comment]
I think about this the other way around: what task do they make sense for? Because it's not clear to me what their intended purposes is from reading the documentation [here](https://albumentations.ai/docs/getting_started/bounding_boxes_augmentation/) nor the docstring itself:

>     label_fields (list): list of fields that are joined with boxes, e.g labels.
>        Should be same type as boxes.

The only purpose that comes to my mind is for tracking who's who if there's the possibility that your Compose pipeline makes one or more boxes disappear. Are there other use cases for the label fields?
