### ISSUE TITLE
RandomResizedCrop should respect additional targets

### ISSUE THREAD

**Issue by Ir1d** [albumentations-team/albumentations#695]
## 🐛 Bug

In https://albumentations.readthedocs.io/en/latest/_modules/albumentations/augmentations/transforms.html the implementation only checks where the main image could be cropped, I think it would be better if shapes of additional targets are also considered.

## To Reproduce

1.
1.
1.

## Environment

 - Albumentations version (e.g., 0.1.8):
 - Python version (e.g., 3.7):
 - OS (e.g., Linux):
 - How you installed albumentations (`conda`, `pip`, source):
 - Any other relevant information:

**Comment by Dipet** [comment]
I do not understand what you mean.
Additional targets needs if you want to create crop of few images with equal crop parameters.
If we simplify transform logic it will be looks like this:
```python
import numpy as np

images = [np.random.randint(0, 256, [100, 100, 3]) for i in range(10)]
x_min, x_max = 10, 20
y_min, y_max = 55, 73

result = [i[y_min:y_max, x_min, x_max] for i in images]
```

**Comment by Ir1d** [comment]
@Dipet 
I understand they should use equal crop parameters. I mean that while determining the params, it should also consider the shape of the additional images (ex: when they are much smaller)

**Comment by Dipet** [comment]
The main idea for additional targets is different.
Current idea, that all additional images must be the same shape.
If you need to apply same transformation on different targets with different shapes in the main it would be wrong.
I think you was confused because scale parameter is shape independent.
To change current behavior we need to make a lot of changes to our main code. And I do not that they are needed.

I think, that we can to rewrite you pipeline with our current API, if you describe what you want.

**Comment by Ir1d** [comment]
In my case, I'd like to perform a same random resized crop on 2 images of different size..
I can rewrite my pipeline with current API, but I think the current design could be improved if the cropping parameters also consider the additional targets.
