### ISSUE TITLE
has anyone tried porting albumentations to jax #question

### ISSUE THREAD

**Issue by narain1** [albumentations-team/albumentations#796]

**Comment by creafz** [comment]
Hey, @narain1 

I have started porting functional augmentations from Albumentations to PyTorch while working on AutoAlbument because I needed augmentations differentiable w.r.t. their parameters. You can find the code here - https://github.com/albumentations-team/autoalbument/tree/master/autoalbument/albumentations_pytorch

This could be a starting point for porting them to JAX, but currently, we do not have plans to use JAX.
