### ISSUE TITLE
Resize mask should not use nearest method of opencv

### ISSUE THREAD

**Issue by shuyangyue** [albumentations-team/albumentations#850]
I'm using this project to train my segmentation model. I find that the mask has a right-down offset to the image. Because the opencv resize_nearest is wrong. Please refer the opencv project issue:  
[https://github.com/opencv/opencv/issues/9096](url)
[https://github.com/opencv/opencv/issues/10146](url)

The code of opencv is:
`    for( x = 0; x < dsize.width; x++ )
    {
        int sx = cvFloor(x*ifx);
        x_ofs[x] = std::min(sx, ssize.width-1)*pix_size;
    }`
It's not the nearest, so it will be a offset between image and mask.

Mask uses the resize nearest in Pillow has no offset to the image. 
Using the resize nearest of opencv to train segmentation model will have a bad result.

**Comment by BloodAxe** [comment]
That's a good point which is worth investigation. From what I know, our library were key component in winning many image segmentation competitions and getting SOTA results on some segmentation benchmarks. Therefore even if there is an issue with NN interpolation of masks, the impact on trained model accuracy is not so obvious. Since one pixel offset is rarely the biggest problem. 

I can think of having `nearest-pillow` interpolation mode, but the effort in implementing this feature is not clear at this point. There are lot of usages of OpenCV interpolation under the hood in many augmentations. Would it be possible to you to run ablation study and demonstrate how big the change in accuracy of the segmentation mask for OpenCV and Pillow interpolation modes are?

**Comment by shuyangyue** [comment]
Thank you for your reply. There is no effect on the iou accuracy of segmentation model. Because mask using opencv resize_nearest causes the ground truth has an offset. If I use the model to predict a image, the result will have about one pixel offset in my model. Examples are below. Left is using the origin albumentations library. Right is pillow resize nearest mode. 
![tmp](https://user-images.githubusercontent.com/13464354/110070815-bee28180-7db5-11eb-98aa-3bfbeee7626e.jpg) ![tmp2](https://user-images.githubusercontent.com/13464354/110070819-c1dd7200-7db5-11eb-94ac-2aedcdfeb0c8.jpg)
It's more obvious when resize mask to a very small size. If input is large, it will be not obvious.  Resize-nearest in pillow or opencv will have no effect on the iou accuracy, because it affects the ground truth.

**Comment by BloodAxe** [comment]
It seems we can use `cv2.INTER_NEAREST_EXACT` interpolation mode to be consistent with PIL, scikit-image or Matlab. @Dipet @creafz @ternaus what are your thoughts on this?

**Comment by ternaus** [comment]
Works for me.

**Comment by creafz** [comment]
I do agree that we need a way to fix the current behavior of OpenCV's nearest interpolation that we use for masks. 

However, we need a way to inform the current users of different behaviors of `cv2.INTER_NEAREST` and `cv2.INTER_NEAREST_EXACT` and let them choose the one they prefer. By following this path, we will not introduce a sudden significant change that will break the current behavior of augmentation pipelines (even if the current behavior is not optimal and may be seen as 'buggy', it is still how Albumentations resizes masks since the first release).

So my proposal is the following:
1. Add a way for users to specify the interpolation algorithm for masks. For example, we could use a parameter for `A.Compose`, e.g.
```
transform = A.Compose([...], mask_interpolation=cv2.INTER_NEAREST_EXACT)
```
2. In the nearest (no pun intended) release of Albumentations, add a warning which says that the next release will use `cv2.INTER_NEAREST_EXACT` instead of `cv2.INTER_NEAREST` for mask interpolation, and to preserve the old behavior, the user must explicitly specify the mask interpolation method for an augmentation pipeline. Let's make a separate article in the documentation that tells the difference between those interpolation methods.
3. After that, in a new release, we will change the default interpolation method to `cv2.INTER_NEAREST_EXACT`, but still, show a warning if the user didn't specify the interpolation method and Albumentations used the default value.

**Comment by Devs-username** [comment]
I'm very hungry

**Comment by Devs-username** [comment]
> I'm using this project to train my segmentation model. I find that the mask has a right-down offset to the image. Because the opencv resize_nearest is wrong. Please refer the opencv project issue:
> [https://github.com/opencv/opencv/issues/9096](url)
> [https://github.com/opencv/opencv/issues/10146](url)
> 
> The code of opencv is:
> ` for( x = 0; x < dsize.width; x++ ) { int sx = cvFloor(x*ifx); x_ofs[x] = std::min(sx, ssize.width-1)*pix_size; }`
> It's not the nearest, so it will be a offset between image and mask.
> 
> Mask uses the resize nearest in Pillow has no offset to the image.
> Using the resize nearest of opencv to train segmentation model will have a bad result.

**Comment by Devs-username** [comment]
[o.o.pdf](https://github.com/albumentations-team/albumentations/files/6346269/o.o.pdf)

**Comment by aksg87** [comment]
@creafz do you know if `mask_interpolation` is going to be added? Any recommendations on current best practice for most segmentation problems?

**Comment by creafz** [comment]
Hey, @aksg87 

We are working on it, but currently, I don't have an ETA for this feature. As a baseline, I think you could stick to the current behavior of Albumentations, which seems to work reasonably well in practice.

**Comment by aksg87** [comment]
> Hey, @aksg87 
> 
> We are working on it, but currently, I don't have an ETA for this feature. As a baseline, I think you could stick to the current behavior of Albumentations, which seems to work reasonably well in practice.

Great! Yes I have used the baseline with a lot of success. Just curious if I should change default types for some optimization

**Comment by karthik1145** [comment]
Has this issue been solved?

**Comment by Dipet** [comment]
Unfortunately, this issue has not been fixed yet.

**Comment by karthik1145** [comment]
Can I try to fix it?

**Comment by zhangwenwen** [comment]
May be it can be done by replacing  ```mask_new = cv2.resize(mask_old, (w, h), cv2.INTER_NEAREST)```  with ```mask_new = cv2.resize(mask_old, (w, h), interpolation=cv2.INTER_NEAREST)```,  but I have not found the reason yet.

**Comment by zhangwenwen** [comment]
Code:
```
mask = np.load(label['mask_file'])
mask1 = cv2.resize(mask, (600,600), interpolation=cv2.INTER_NEAREST)
mask2 = cv2.resize(mask, (600,600), cv2.INTER_NEAREST)
```
Results:
![mask](https://user-images.githubusercontent.com/8948724/228415111-87dcc791-172f-467e-bcf0-fcf77766c949.png)
![mask1](https://user-images.githubusercontent.com/8948724/228415152-456005fb-a3a0-43c8-908e-8664cfefad2f.png)
![mask2](https://user-images.githubusercontent.com/8948724/228415167-8f6884a9-cb28-465c-9dfe-f406372c3a0b.png)

**Comment by ternaus** [comment]
@shuyangyue @aksg87 @karthik1145 @zhangwenwen 

- Added an option to choose interpolation for mask for every transform that has `mask_interpolation`
- Added an option to define `mask_interpolation` in Compose that overrides ones defined in individual transforms
