### ISSUE TITLE
Customized augmentation

### ISSUE THREAD

**Issue by DrX2020** [albumentations-team/albumentations#857]
Currently I am doing object detection with MMDetection. I found an example that indicates how to use albumentation in MMDetection: ./mmdetection/configs/albu_example/mask_rcnn_r50_fpn_albu_1x_coco.py (file has been attached). I managed to implement some augmentations in albumentations according to this file. Now I want to try a new augmentation, copy and paste. The link (https://github.com/conradry/copy-paste-aug) gives "transform = A.Compose". It is different from the contents in the file "mask_rcnn_r50_fpn_albu_1x_coco.py", which use class Albu in MMDetection and easily implement any augmentations as long as albumentation is installed. For now I have not figured out how to implement copy and paste in albumentations.
[mask_rcnn_r50_fpn_albu_1x_coco.zip](https://github.com/albumentations-team/albumentations/files/6163873/mask_rcnn_r50_fpn_albu_1x_coco.zip)

**Comment by Dipet** [comment]
Hello!
They are different because you write config, not the pipeline code.
These augmentation does not implemented inside library so I think it is impossible to describe it using these config. For more information on how to describe a custom transformation within configurations, I advise you to ask this question in the MMDetection library

**Comment by DrX2020** [comment]
Thank you!
