### ISSUE TITLE
ModuleNotFoundError: No module named 'albumentations'  - in jupyter notebook only

### ISSUE THREAD

**Issue by longwall** [albumentations-team/albumentations#895]
## To Reproduce

1. Start  jupyter notebook  or  jupyter lab
2. try to import any library part in a new cell : from albumentations.augmentations import transforms
3. get the error: ModuleNotFoundError: No module named 'albumentations'
4. Check that  the library is in the environment:  $ conda list | grep alb  # should return
albumentations            0.5.2                    pypi_0    pypi
5. In bash session: python , then type from albumentations.augmentations import transforms
6. Make sure that the library is included in python shell

## Expected behavior

In jupyter session the labrary should be included without error

## Environment

 - Albumentations version (e.g., 0.1.8): 0.5.2
 - Python version (e.g., 3.7):
 - OS (e.g., Linux):  WSL2, Ubuntu
 - How you installed albumentations (`conda`, `pip`, source): pip
 - Any other relevant information:

**Comment by iswarup** [comment]
Hello people!
Any solution updates here?
I'm facing the same issue

Albumentations version 1.1.0
Python version 3.9.12
Windows 11
pip 21.2.4

**Comment by Dipet** [comment]
Did you try to install or upgrade library using pip?
Try this command: `pip install --upgrade albumentations`

**Comment by iswarup** [comment]
I found the solution that the package was getting installed at an unexpected location as below
C:\Users\Swarup\AppData\Roaming\Python\Python39\site-packages

The expected location for [pip install albumentations] was as below
C:\Users\Swarup\Anaconda3\Lib\site-packages

So I just copied the folders from the first location to second one. And the problem's solved! :D
Following six packages were installed so while copying them I skipped cv2 since I already had it at the dst 

![image](https://user-images.githubusercontent.com/10144957/170884776-511b0c0b-7b0c-4c66-ab19-350988708268.png)


Even so I'd like to understand why the first location was selected for the installation in the first place!
Both are user level installations.

**Comment by haddagart** [comment]
> 

I did try the upgrade. The problem isn't with the code or something because I tried force installing an earlier version on Google Colab and it worked fine with the proper openCV version. Yet, the problem is at the installation location and the version signature. The upgrade should remove the existing version and replace it with an earlier code. Actually, what is happening is quite different. The issue that @iswarup pointing too is exact and the behavior of the installation, updates, and upgrades doesn't seem to work correctly on managing the site-packages as it is supposed to do.

I hope that my comment clarified the problem

**Comment by PallobPoddar** [comment]
Thanks a lot @iswarup I was facing the same problem and now it has been fixed

**Comment by Daryldactyl** [comment]
I used %pip install albumentations instead of !pip install albumentations inside the venv and that finally fixed it for me after restarting the kernel!

**Comment by ternaus** [comment]
I do not think that there is an issue with `albumentations` but some misunderstanding of how and where python packages are installed with  different environments.

**Comment by medinanicolas** [comment]
> I do not think that there is an issue with albumentations but some misunderstanding of how and where python packages are installed with different environments.

Yes, in my case, I had Jupyter installed globally on Windows. After installing it with `python -m pip install notebook` inside the Conda environment and `python -m jupyter notebook .` everything works.
